# Generated by Django 6.0.2 on 2026-02-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='Canciones/')),
                ('duracion', models.IntegerField(help_text='Duracion en segundos')),
            ],
        ),
    ]
