# Generated by Django 6.0.2 on 2026-02-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cancion',
            new_name='Canciones',
        ),
    ]
