# Generated by Django 6.0.2 on 2026-02-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_rename_cancion_canciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='canciones',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
