# Generated by Django 6.0.2 on 2026-02-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_canciones_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canciones',
            name='duracion',
        ),
    ]
